### ISSUE TITLE
Fail to compile on OS X 10.11 beta 6 with Rustc 1.2.0-nightly (31d9aee68 2015-06-22)

### ISSUE THREAD

**Issue by Axure** [drrb/rust-netbeans#13]
When using `mvn package`:

> Changes detected. Compiling all Rust crates!
> Compiling crate src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs
> Running command: [rustc, --out-dir, target/rust-libs, src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs]
> src/main/rust/com/github/drrb/javarust/lib/compiler.rs:15:5: 15:28 error: unresolved import `syntax::ast_map::Forest`. Could not find `ast_map` in `syntax`
> src/main/rust/com/github/drrb/javarust/lib/compiler.rs:15 use syntax::ast_map::Forest;
>                                                               ^~~~~~~~~~~~~~~~~~~~~~~
> error: aborting due to previous error

**Comment by cevarief** [comment]
~~~
Compiling crate src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs
Running command: [rustc, --out-dir, target/rust-libs, src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs]
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:18:1: 18:25 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:18 #![feature(collections)]
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:19:1: 19:18 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:19 #![feature(core)]
                                                                ^~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:20:1: 20:18 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:20 #![feature(libc)]
                                                                ^~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:21:1: 21:22 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:21 #![feature(old_path)]
                                                                ^~~~~~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:22:1: 22:27 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:22 #![feature(rustc_private)]
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:23:1: 23:22 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:23 #![feature(std_misc)]
                                                                ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to 6 previous errors
[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: rustc exited nonzero (status code = 101)
	at com.github.drrb.rust.netbeans.build.CompileRustCrates.compile(CompileRustCrates.java:68)
	at com.github.drrb.rust.netbeans.build.CompileRustCrates.main(CompileRustCrates.java:49)
	... 6 more
~~~

**Comment by drrb** [comment]
Closing. I believe this was due to using non-nightly Rust. Shouldn't be an issue with more recent versions of the plugin.
